/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#de245b",
        "on-secondary-fixed-variant": "#8c1038",
        "secondary-fixed-dim": "#ffb2bd",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f6f2fc",
        "background": "#fcf8ff",
        "on-primary-fixed-variant": "#910034",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#ad2c4f",
        "outline": "#8f6f73",
        "surface-container-high": "#ebe6f1",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#fd6989",
        "surface-container-highest": "#e5e1eb",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#002113",
        "tertiary": "#006947",
        "primary": "#b80045",
        "on-background": "#1c1b22",
        "on-tertiary-container": "#f5fff6",
        "primary-fixed-dim": "#ffb2bc",
        "outline-variant": "#e3bdc1",
        "surface-bright": "#fcf8ff",
        "secondary-fixed": "#ffd9dd",
        "on-secondary-container": "#6b0027",
        "on-primary-fixed": "#400012",
        "surface-tint": "#bd0047",
        "inverse-surface": "#312f37",
        "tertiary-fixed-dim": "#4edea3",
        "primary-fixed": "#ffd9dd",
        "tertiary-container": "#00855b",
        "tertiary-fixed": "#6ffbbe",
        "on-error": "#ffffff",
        "on-surface-variant": "#5b4043",
        "on-secondary-fixed": "#400014",
        "surface-dim": "#ddd8e3",
        "on-surface": "#1c1b22",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb2bc",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container": "#f1ecf6",
        "surface": "#fcf8ff",
        "surface-variant": "#e5e1eb",
        "inverse-on-surface": "#f4eff9",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.75rem",
        "margin-tablet": "2rem",
        "gutter-tablet": "1.5rem",
        "space-xl": "1.5rem",
        "gutter-mobile": "1rem",
        "space-2xl": "2rem",
        "space-lg": "1.25rem",
        "space-3xl": "2.5rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        "space-2xs": "0.25rem"
      },
      fontFamily: {
        "sans": ["Plus Jakarta Sans", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        "bloom-1": "0 4px 20px -2px rgba(255, 64, 113, 0.06), 0 1px 3px 0 rgba(18, 17, 24, 0.03)",
        "bloom-2": "0 12px 32px -4px rgba(255, 64, 113, 0.12), 0 4px 8px -2px rgba(18, 17, 24, 0.04)",
        "bloom-3": "0 20px 48px -6px rgba(18, 17, 24, 0.16)",
      },
    },
  },
  plugins: [],
}
